### ISSUE TITLE
Run Application with one command

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/PDP-Monitoring-System#20]
[comment]: # (Reminder: Add to a milestone)
[comment]: # (Reminder: add labels)

# Description
[comment]: # (Describe what the feature or bug that need to be resolved)
[comment]: # (List if applicable: libraries, sensors, hardware, small parts of code you have to work on)

Create a bash script that runs everything in one command. Take it one step further and get it to run on startup. Would love to dockerize it but serial and labjack is a no go because there external devices

# Acceptance Criteria
[comment]: # (Write specifically what is need for this issue to be completed)

- [x] command runs `serail-main.py`, `read-labjack.py`, `instrumentation-web-socket.py` and starts ground support see `start_gui.sh`
- [x] command runs successfully on start up

# QA Notes
[comment]: # (how to test your ticket)

## Linked issues
[comment]: # (If there are any related or blocker issues)

Blocked by the PR

**Comment by klemie** [comment]
@jjderooy made this. but it has seemed to cause a bug or is part of a bug. Now we cant send serial and have instrumentation running at the same time. Might need to investigate this more.

**Comment by jjderooy** [comment]
Ok I fogor to commit and push the bash file I made on the mini pc but I know what the problem is. Basically, `&` on the end of a bash command (like the ones starting the python scripts) starts that in a new process in the background. When doing ctrl-c in the terminal shown by running the bash script, it only terminates the foreground process and not the background processes.

We can fix this by `trap`ing the ctrl+c input to run a command before exiting the bash script like this:

### start.sh
```bash
trap ctrl_c INT

function ctrl_c() {
    echo "Trapped CTRL_C"
    kill -INT $PID1 $PID2 $PID3... # Send interrupt signal to each process
}

# Rest of original script here:
python read_labjack.py &
python ws.py &
...
 ```
I'll try and test this tmr and push it if it works.

**Comment by jjderooy** [comment]
I tested this among other variations and cannot for the life of me get it to work. Pressing ctrl+c interrupts the bash process, and then when the signal is trapped, it errors on `kill -INT` saying the PIDs aren't found. I'll have to do some more testing.

**Comment by jjderooy** [comment]
Done. I ended up not using bash and instead using python subprocesses.
